### ISSUE TITLE
Code License & Copyright

### ISSUE THREAD

**Issue by stephenrauch** [tinkermachine/Saturn#1]
If you are going to copy copyrighted code, you need maintain the license for said code.  This repo has code from the [pycel repo](https://github.com/dgorissen/pycel), but you have not copied any of the copyright notices or license files.  Please do not do this.  Please do not make the owners of said copyright go to the trouble of filing a DMCA notice to github to remove this repo.

Please fix this ASAP.

Thanks.

**Comment by tinkermachine** [comment]
Thank you for pointing this out! I have copied over the LICENSE file into
my repo, but please let me know if there is anything else I need to do.
